name: "JavaCombat"
version: "1.0.0-SNAPSHOT"
description: "JavaCombat plugin by MaXoNeRYT"
api: ["1.0.0"]
author: MaXoNeRYT
website: https://github.com/MaXoNeRYT
main: "md.maxoneryt.javacombat.JavaCombat"